### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by raideltorres** [gre/gl-transition-libs#32]
Hi guys, I know this is not the place to ask, but this is not a subject really talked in stackoverflow . . . so please let me ask here . . . I'm trying to create a really simple example . . . like this 

```
const from = 'https://i.imgur.com/wxqlQkh.jpg';
const to = 'https://i.imgur.com/iPKTONG.jpg';
const transition = GLTransitions[0];
const progress = 0.5;

<GLTransition
    from={from}
    to={to}
    progress={progress}
    transition={transition}
/>
```

I know the Transition is not properly set, but I can't find the way to set it properly and I'm probably doing 100 more things wrong . . .

**Comment by gre** [comment]
I don't really understand the question. not properly set? 🤔

**Comment by raideltorres** [comment]
yeah sorry, my question is really what I'm doing wrong there . . .

**Comment by gre** [comment]
Can you list the exact version of libs your project is using?

yarn list gl-*

Or

npm ls gl-*

**Comment by raideltorres** [comment]
Yeah sure

├─ gl-constants@1.0.0
├─ gl-format-compiler-error@1.0.3
├─ gl-react-color-blending@2.0.5
├─ gl-react-expo@3.16.3
├─ gl-react-image@3.1.1
├─ gl-react@3.15.0
└─ gl-shader@4.2.1

**Comment by ReactGirl** [comment]
@raideltorres Have you been able to solve your example? Can you show the solution?

**Comment by raideltorres** [comment]
no sorry I ended using something different since the client was flexible.

But per documentation is should be like this

## API

This exposes a simple `GLTransition` react component you have to use inside gl-react `Surface`.
It renders one frame of the transition (up to you to run the animation loop the way you want).

```html
<GLTransition progress={progress} from={from} to={to} transition={transition} />
```
