### ISSUE TITLE
gltransition not working properly for 480p 

### ISSUE THREAD

**Issue by yukesh0505** [gre/gl-transition-libs#36]
hai,
actually am using gltransition through ffmpeg all transition are working properly for 1080p and 720p but at the same time 420p resolution fails for square videos too, is there any particular reason for that please reply ASAP

![screencapture-test-multimedia5-producedvideo-2019-04-12-16_43_51 (1)](https://user-images.githubusercontent.com/46150058/56033510-637ef480-5d42-11e9-92f5-e2e8bc7664cd.png)
Above screenshot at transition between slide at duration of 1 second

**Comment by gre** [comment]
please report on https://github.com/transitive-bullshit/ffmpeg-gl-transition
