### ISSUE TITLE
ZEIT now broken links

### ISSUE THREAD

**Issue by transitive-bullshit** [gre/gl-transition-libs#45]
The website used to support linking ala [https://gl-transitions.com/editor/circleopen](https://gl-transitions.com/editor/circleopen), but it appears this was broken in a recent release.

I'm linking to these transitions from [ffmpeg-concat](https://github.com/transitive-bullshit/ffmpeg-concat#transitions-1) and had a user point this out to me.

Should be a pretty quick fix -- I ran into this previously on a different project, and I think you can change the deployment template in settings on ZEIT now.

thanks!

**Comment by gre** [comment]
I don't see how to enable it :'(

I feel i need to add a special config in the github project 🤔

**Comment by transitive-bullshit** [comment]
This is how I did it for a SPA. Note the preset set to Create React App.

<img width="808" alt="Screen Shot 2020-03-29 at 5 01 39 AM" src="https://user-images.githubusercontent.com/552829/77845161-86383200-717a-11ea-83b9-e50513f79c97.png">

**Comment by gre** [comment]
@transitive-bullshit i tried it last week and in fact i forgot to retrigger a build! it works now! thanks

**Comment by transitive-bullshit** [comment]
Awesome haha 😂
